### ISSUE TITLE
Driver [b2] is not supported.

### ISSUE THREAD

**Issue by JunaidQadirB** [bringyourownideas/laravel-backblaze#4]
I'm using Laravel 8
I've installed the package.
Added the `b2` key to the `filesystems.php`
Add settings from my backblaze to the `.env` file
cleared the cache
But when I run the app with this code

```php
$fakeImage = $this->faker->image();
$fakeImageFile =  new File($fakeImage);
Storage::disk('b2')->putFile('images', $fakeImageFile);
```
I get an `InvalidArguementException` Exception with this message: `Driver [b2] is not supported.`

**Comment by spekulatius** [comment]
Hello @JunaidQadirB 

interesting, I use it mostly with spatie backup in combination. Could you run `php -v` and `composer show` to see which exact versions you are running?

Happy New Year!

Peter

**Comment by jpmurray** [comment]
Hello, new user of the package chiming in, thought I'd give feedback... I'm on Laravel 8, all's good and working on my end ;-)

**Comment by spekulatius** [comment]
Hey @jpmurray and @JunaidQadirB 

okay, sounds good. Atm I don't have a project to test it on proper. I'll add 8.0 to the master branch so the installation is possible. If no issues arise I'll tag a release shortly too.

Cheers,
Peter

**Comment by spekulatius** [comment]
Hey @jpmurray and @JunaidQadirB,

I've tested it without any trouble. I've tagged a release.

@JunaidQadirB does your problem still persist?

Cheers,
Peter

**Comment by JunaidQadirB** [comment]
My apologies. Actually I tried it and when it didn't work so moved on since we have deadline.

I might test it again in a few weeks and update.

Cheers

**Comment by spekulatius** [comment]
No problem! Let's close the issue for now. Feel free to raise a new one or reopen if you decide to retry.
