### ISSUE TITLE
Can't use an application key

### ISSUE THREAD

**Issue by jpmurray** [bringyourownideas/laravel-backblaze#5]
Hello !

Trying to use the adapter with an application key seems to always result in an `unauthorized` error... But working with the master application key works perfectly fine. Is this normal ?

**Comment by spekulatius** [comment]
Hey @jpmurray,

yes, it doesn't work with application keys atm. This was already like this when I fixed it to get it working again.

Cheers,
Peter

**Comment by jpmurray** [comment]
Thank you for confirming, @spekulatius ! ;-)

**Comment by spekulatius** [comment]
No problem! :+1:
