### ISSUE TITLE
Started getting 404 on API endpoints, anyone else?

### ISSUE THREAD

**Issue by jpmurray** [bringyourownideas/laravel-backblaze#7]
Specifically:

```
GuzzleHttp\Exception\ClientException: Client error: `GET https://api.backblazeb2.com/b2api/v1//b2_authorize_account` resulted in a `404 Not Found` response:
{
  "code": "not_found",
  "message": "/b2api/v1//b2_authorize_account",
  "status": 404
}
```

Anyone else?

**Comment by spekulatius** [comment]
Hey @jpmurray,

I have to admit I switched completely to the S3 approach as mentioned: https://github.com/bringyourownideas/laravel-backblaze#use-b2-via-s3-instead

Maybe this could help resolving your issues?

Cheers,
Peter

**Comment by jpmurray** [comment]
Ah, yeah, I wanted to use that for a while now, even before using this package actually, but this one just made it so easier. I'll go back and change to the technique soon enough ! ;)

**Comment by spekulatius** [comment]
Yeah, understandable. I've used this package for a long time too because it made stuff easier for me as well. Going back to configuration only keeps the codebases cleaner in the long run tho. Hence my decision to drop it at the end.

**Comment by jpmurray** [comment]
Oh yeah, 100% agrees with you on that ! :)
